Fix imu problem in gazebo simulation.
rm-controls/rm_control pull request #107
Opened 2023-03-05 03:18 UTC by chenhuiYu00

在gazebo对平衡步兵的仿真中会出现当有两块imu时，其中一块的数据会始终是0，在排除是urdf本身的错误后开始排查代码。

chassis controller会向interface获取base imu的handle，这个handle的数据会在rm_gazebo包内的readSim()函数内更新。检查变量地址后发现函数内更新的变量内存地址和handle尝试读取的内存的地址不一样.

经过[[c++查询](https://en.cppreference.com/w/cpp/container/vector)](https://en.cppreference.com/w/cpp/container/vector)，发现vector容器的元素内存地址会在程序的运行中进行随机分配

```c
“The storage of the vector is handled automatically, being expanded as needed. Vectors usually occupy more space than static arrays, because more memory is allocated to handle future growth. This way a vector does not need to reallocate each time an element is inserted, but only when the additional memory is exhausted. The total amount of allocated memory can be queried using capacity() function. Extra memory can be returned to the system via a call to shrink_to_fit(). (since C++11)”
```

原文中提到“This way a vector does not need to reallocate each time an element is inserted“，说明vector容器的元素内存地址会在插入元素后随机分配

不过有意思的是第一个元素地址并不会变化，这也就导致了从第二个元素开始才会有问题。

通过与can bus的数据存储比较，发现can数据使用map容器存储，这也许是can数据不会有问题的原因。

解决方案一：使用动态内存分配，imu容器内部元素类型为指针，尽管指针变量的地址会变，但其指向仍是动态分配的内存地址

解决方案二：使用reserve()函数，在vector插入元素前预分配足够的内存，避免元素内存地址在插入元素后随机分配(目前采用的方案)

以上两种方案都通过了测试

2023-03-05 04:19 UTC, ye-luo-xi-tui commented
晨辉哥太牛啦
值得一提的是gazebo_ros_control在初始化时会对vector使用resize()函数，应该也是相同的作用

2023-03-05 04:20 UTC, ye-luo-xi-tui approved these changes

2023-03-05 06:50 UTC, qiayuanliao requested changes
很不错的工作。

不过建议直接用 list，可以参考 [这个](https://github.com/qiayuanliao/legged_control/blob/master/legged_gazebo/include/legged_gazebo/LeggedHWSim.h#LL89C20-L89C20) ，我在这里修复了这个锅然后忘记改rm的了。

2023-03-06 05:20 UTC, chenhuiYu00 commented
> 很不错的工作。
> 
> 不过建议直接用 list，可以参考 [这个](https://github.com/qiayuanliao/legged_control/blob/master/legged_gazebo/include/legged_gazebo/LeggedHWSim.h#LL89C20-L89C20) ，我在这里修复了这个锅然后忘记改rm的了。

好的，我已经用list替换了vector并进行了测试

2023-03-07 08:37 UTC, qiayuanliao approved these changes
很好！

2023-03-08 06:32 UTC, merged