Add a robot communication to set sentry state.
rm-controls/rm_control pull request #117
Opened 2023-03-21 12:20 UTC by NaHCO3bc

添加给哨兵设置原地小陀螺的车间通信，通信已测试完成，referee功能正常，可以正常通过ManualToReferee话题和manual通信并通过车间通信发出。定义新的triggerui时写了画ui的接口，但还没有测试过画ui的部分，后续根据需求再考虑是否需要画ui。如果需要画UI的话可能需要哨兵通过车间通信发送一个实时的哨兵状态

2023-03-22 17:38 UTC, ye-luo-xi-tui commented on rm_referee/include/rm_referee/ui/trigger_change_ui.h
> +  ros::Publisher sentry_state_pub_ = state_nh_.advertise<rm_msgs::ManualToReferee>("/state", 10);
令人智熄

2023-03-24 17:20 UTC, ye-luo-xi-tui commented
配好pre-commit！

2023-03-28 06:14 UTC, Edwinlinks commented
为啥要哨兵实时的发送状态，状态改变的时候发一次不行吗

2023-03-28 06:14 UTC, Edwinlinks commented
ui那个有测过了不

2023-03-28 07:52 UTC, NaHCO3bc commented
> 为啥要哨兵实时的发送状态，状态改变的时候发一次不行吗

现在是改变一次发一次呀

2023-03-28 07:56 UTC, NaHCO3bc commented
> ui那个有测过了不

还没捏 我想如果要画ui的话要不加多个topic，fsm里状态改变了就发topic给车间通信，然后步兵英雄订阅这个topic来画ui；如果是现在的代码的话，这个ui是由步兵英雄上从manual里发给referee的topic改变的，感觉准确性不太行

2023-03-30 06:41 UTC, Edwinlinks commented on rm_referee/include/rm_referee/referee_base.h
> +  SentryInteractiveDataTriggerChangeUi* sentry_interactive_data_trigger_change_ui{};
代码规范

2023-03-30 07:30 UTC, Edwinlinks commented on rm_referee/src/referee_base.cpp
> +      nh.subscribe<rm_msgs::SentryData>("/sentry/state", 10, &RefereeBase::sentryDataCallBack, this);
你这里从哨兵那里收数据的topic名字改成 fsm_to_referee之类的吧，我想了一下最好不要也叫state

2023-03-30 07:44 UTC, Edwinlinks commented on rm_referee/src/ui/trigger_change_ui.cpp
> +void SentryInteractiveDataTriggerChangeUi::display()
这个display是在哪里调用的？

2023-03-30 07:45 UTC, NaHCO3bc commented on rm_referee/src/referee_base.cpp
> +      nh.subscribe<rm_msgs::SentryData>("/sentry/state", 10, &RefereeBase::sentryDataCallBack, this);
> 你这里从哨兵那里收数据的topic名字改成 fsm_to_referee之类的吧，我想了一下最好不要也叫state

这里是步兵英雄上从manual发给referee的那个topic

2023-03-30 07:47 UTC, Edwinlinks commented
> > ui那个有测过了不
> 
> 还没捏 我想如果要画ui的话要不加多个topic，fsm里状态改变了就发topic给车间通信，然后步兵英雄订阅这个topic来画ui；如果是现在的代码的话，这个ui是由步兵英雄上从manual里发给referee的topic改变的，感觉准确性不太行

为啥说“这个ui是由步兵英雄上从manual里发给referee的topic改变的”？应该是成功发送了一次fsm 改变转变状态的interactive data 就display一次吧？显示一个已发送

2023-03-30 07:52 UTC, NaHCO3bc commented
> > > ui那个有测过了不
> > 
> > 
> > 还没捏 我想如果要画ui的话要不加多个topic，fsm里状态改变了就发topic给车间通信，然后步兵英雄订阅这个topic来画ui；如果是现在的代码的话，这个ui是由步兵英雄上从manual里发给referee的topic改变的，感觉准确性不太行
> 
> 为啥说“这个ui是由步兵英雄上从manual里发给referee的topic改变的”？应该是成功发送了一次fsm 改变转变状态的interactive data 就display一次吧？显示一个已发送

是应该这样，只是之前没有主要去写ui的部分，一开始写成了由步兵英雄上的topic改变而改变就没改过了

2023-03-30 07:54 UTC, Edwinlinks commented on rm_referee/src/referee_base.cpp
> +      nh.subscribe<rm_msgs::SentryData>("/sentry/state", 10, &RefereeBase::sentryDataCallBack, this);
> > 你这里从哨兵那里收数据的topic名字改成 fsm_to_referee之类的吧，我想了一下最好不要也叫state
> 
> 这里是步兵英雄上从manual发给referee的那个topic

噢，OK，那名字还是改改吧

2023-03-31 17:50 UTC, NaHCO3bc commented
新添加了与哨兵车间通信的反馈结果的相关函数，测试过后车间通信大致正常，但会出现车间通信无法实时输出或直接不输出
即英雄哨兵发出命令后，哨兵无法正常或及时收到车间通信的信号或哨兵收到车间通信信号后发出的反馈无法被英雄和步兵收到。（个人认为受到串口通信的带宽限制）
这个问题会导致两种情况：
* 步兵英雄发出命令后，哨兵无法收到，那也就不会有反馈，ui也不会改变
* 哨兵收到命令后，步兵英雄无法收到反馈，ui不会变化且与哨兵真实状态不符
ui方面是英雄步兵收到的哨兵通过车间通信发来的信号后再画ui，功能正常。

2023-03-31 19:36 UTC, ye-luo-xi-tui approved these changes

2023-04-01 10:10 UTC, qiayuanliao requested changes
你定义了一个只有 uint8 的消息作甚？直接用 [std_msgs/UInt8](http://docs.ros.org/en/noetic/api/std_msgs/html/msg/UInt8.html) 就行啊！

2023-04-01 10:17 UTC, NaHCO3bc commented
> 你定义了一个只有 uint8 的消息作甚？直接用 [std_msgs/UInt8](http://docs.ros.org/en/noetic/api/std_msgs/html/msg/UInt8.html) 就行啊！

好像是耶，但凯子哥说可能以后会再加其他消息进去，现在要改嘛

2023-04-01 10:50 UTC, ye-luo-xi-tui commented
> > 你定义了一个只有 uint8 的消息作甚？直接用 [std_msgs/UInt8](http://docs.ros.org/en/noetic/api/std_msgs/html/msg/UInt8.html) 就行啊！
> 
> 好像是耶，但凯子哥说可能以后会再加其他消息进去，现在要改嘛

直接模仿裁判系统新协议吧， @Edwinlinks 你觉得呢

2023-04-02 02:42 UTC, Edwinlinks commented
> > > 你定义了一个只有 uint8 的消息作甚？直接用 [std_msgs/UInt8](http://docs.ros.org/en/noetic/api/std_msgs/html/msg/UInt8.html) 就行啊！
> > 
> > 好像是耶，但凯子哥说可能以后会再加其他消息进去，现在要改嘛
> 
> 直接模仿裁判系统新协议吧， @Edwinlinks 你觉得呢

就直接模仿新裁判系统的target_position_x吧@NaHCO3bc

2023-04-03 14:35 UTC, qiayuanliao commented on rm_referee/src/ui/trigger_change_ui.cpp
> +    return;
> 不要这样搞！按键是什么就如实转发给哨兵，fsm内部把按键映射成具体功能

是不是可以搞成 按住某个键（如 ctrl），再加上某个键（如 A）就发送 A 给哨兵，其他组合也一样，这样就可以开很多功能给哨兵

2023-04-03 15:02 UTC, ye-luo-xi-tui commented on rm_referee/src/ui/trigger_change_ui.cpp
> +    return;
> > 不要这样搞！按键是什么就如实转发给哨兵，fsm内部把按键映射成具体功能
> 
> 是不是可以搞成 按住某个键（如 ctrl），再加上某个键（如 A）就发送 A 给哨兵，其他组合也一样，这样就可以开很多功能给哨兵

可以

2023-04-05 09:20 UTC, ye-luo-xi-tui commented on rm_msgs/msg/referee/ClientMapReceiveData.msg
> +uint8 SENTRY_INTERACTIVE_RESULT = 2
删掉

2023-04-05 09:28 UTC, ye-luo-xi-tui commented on rm_referee/src/ui/trigger_change_ui.cpp
> +                                                        rm_msgs::ClientMapReceiveData ::SENTRY_INTERACTIVE_DATA,
rm_referee内部定义枚举量吧

2023-04-08 16:59 UTC, qiayuanliao requested changes
1. target_position_z 是干啥滴？哨兵会有 z方向的指令吗？

2. 位置为什么不用 geometry_msgs::Vector3？

2023-04-08 17:02 UTC, qiayuanliao reviewed
题外话：

1. 后面可以把哨兵自己计算出来的自身位置也发出来。
2. 判断机器人的红蓝方、类型等写几个helper函数，不要在那里疯狂 `robot_id > xxxx `   `robot_id == xxx`

2023-04-08 17:03 UTC, qiayuanliao commented
@ye-luo-xi-tui review 质量有点低啊，建议你多看几眼再找我

2023-04-08 17:26 UTC, qiayuanliao commented
另外，你的这整个功能的命名也是匪夷所思的。

我们从没有用过 client（客户端）来指操作手指令相关的东西，我看到client 根本不知道是啥东西，翻译成 客户端 才 get 到。如果用 client 的话，整个 rm_manual 应该改名为 rm_client。

对这种功能应该是按 “机间通讯” 或 “机器人与裁判系统”通讯 的逻辑来的。步兵或工程或 rm_manual 和 裁判系统 (referee) 做交互，哨兵也和 referee 做交互，这根本就没有客户端什么事儿。

客户端只是通过 dbus 发送数据！或收裁判系统的绘制数据！和机器人其实是隔离开的！我觉得短时间内应该不会有任何的代码会需要用 client 这个词

2023-04-08 18:54 UTC, ye-luo-xi-tui commented
> 1. target_position_z 是干啥滴？哨兵会有 z方向的指令吗？
> 
>     2. 位置为什么不用 geometry_msgs::Vector3？

这个是直接和新的裁判系统协议一模一样（事实上旧协议里就有了），分区赛时这个msg会是直接从裁判系统读的。联盟赛过后会将与哨兵的车间通信相关代码删掉。

2023-04-08 18:56 UTC, ye-luo-xi-tui commented
> 另外，你的这整个功能的命名也是匪夷所思的。
> 
> 我们从没有用过 client（客户端）来指操作手指令相关的东西，我看到client 根本不知道是啥东西，翻译成 客户端 才 get 到。如果用 client 的话，整个 rm_manual 应该改名为 rm_client。
> 
> 对这种功能应该是按 “机间通讯” 或 “机器人与裁判系统”通讯 的逻辑来的。步兵或工程或 rm_manual 和 裁判系统 (referee) 做交互，哨兵也和 referee 做交互，这根本就没有客户端什么事儿。
> 
> 客户端只是通过 dbus 发送数据！或收裁判系统的绘制数据！和机器人其实是隔离开的！我觉得短时间内应该不会有任何的代码会需要用 client 这个词

同上，从命名到消息类型都是按裁判系统协议来的。之所以这么做是为了到时fsm不必做过多改动。

2023-04-09 15:36 UTC, qiayuanliao commented
> > 另外，你的这整个功能的命名也是匪夷所思的。
> > 我们从没有用过 client（客户端）来指操作手指令相关的东西，我看到client 根本不知道是啥东西，翻译成 客户端 才 get 到。如果用 client 的话，整个 rm_manual 应该改名为 rm_client。
> > 对这种功能应该是按 “机间通讯” 或 “机器人与裁判系统”通讯 的逻辑来的。步兵或工程或 rm_manual 和 裁判系统 (referee) 做交互，哨兵也和 referee 做交互，这根本就没有客户端什么事儿。
> > 客户端只是通过 dbus 发送数据！或收裁判系统的绘制数据！和机器人其实是隔离开的！我觉得短时间内应该不会有任何的代码会需要用 client 这个词
> 
> 同上，从命名到消息类型都是按裁判系统协议来的。之所以这么做是为了到时fsm不必做过多改动。

了解了，是我忘记 referee 里的都是按裁判系统定义的了，我的锅

2023-04-09 16:50 UTC, qiayuanliao requested changes
SentryInteractiveData 是要表达什么意思？哨兵交互数据？是哨兵状态或者哨兵指令或者哨兵模式吧。晕， GimbalCmd 咋不叫 GimbalInteractiveData 呢？ ShooterCmd 咋不叫 ShooterInteractiveData 哈哈哈哈。

叫 SentryInteractiveUi, 或者 SentryStateUi （更好）吧？

禁止使用翻译软件直接翻译！！！禁止使用翻译软件直接翻译！！！禁止使用翻译软件直接翻译！！！总会有匪夷所思的命名。

不要用 “data” 命名，没有任何意义的一个词，加了和没加都不会改变原本的意思，比如： GimbalCmdData RefereeData。 像 Cmd 和 State 这种后戳才是有意义的。

抽空把现在的 DbusData 改掉，就叫 Dbus 就可以了, 或者DbusState。

2023-04-10 02:18 UTC, NaHCO3bc commented
> SentryInteractiveData 是要表达什么意思？哨兵交互数据？是哨兵状态或者哨兵指令或者哨兵模式吧。晕， GimbalCmd 咋不叫 GimbalInteractiveData 呢？ ShooterCmd 咋不叫 ShooterInteractiveData 哈哈哈哈。
> 
> 叫 SentryInteractiveUi, 或者 SentryStateUi （更好）吧？
> 
> 禁止使用翻译软件直接翻译！！！禁止使用翻译软件直接翻译！！！禁止使用翻译软件直接翻译！！！总会有匪夷所思的命名。
> 
> 不要用 “data” 命名，没有任何意义的一个词，加了和没加都不会改变原本的意思，比如： GimbalCmdData RefereeData。 像 Cmd 和 State 这种后戳才是有意义的。
> 
> 抽空把现在的 DbusData 改掉，就叫 Dbus 就可以了, 或者DbusState。

是因为后续可能会在车间通信中加入位置信息之类的其他信息，不只是状态信息，所以用了data这个比较概括性的词。interactive是主要为了体现它是通过交互实现的，想着和其他在一辆车上实现的功能区分一下

2023-04-10 15:22 UTC, qiayuanliao commented
> > SentryInteractiveData 是要表达什么意思？哨兵交互数据？是哨兵状态或者哨兵指令或者哨兵模式吧。晕， GimbalCmd 咋不叫 GimbalInteractiveData 呢？ ShooterCmd 咋不叫 ShooterInteractiveData 哈哈哈哈。
> > 叫 SentryInteractiveUi, 或者 SentryStateUi （更好）吧？
> > 禁止使用翻译软件直接翻译！！！禁止使用翻译软件直接翻译！！！禁止使用翻译软件直接翻译！！！总会有匪夷所思的命名。
> > 不要用 “data” 命名，没有任何意义的一个词，加了和没加都不会改变原本的意思，比如： GimbalCmdData RefereeData。 像 Cmd 和 State 这种后戳才是有意义的。
> > 抽空把现在的 DbusData 改掉，就叫 Dbus 就可以了, 或者DbusState。
> 
> 是因为后续可能会在车间通信中加入位置信息之类的其他信息，不只是状态信息，所以用了data这个比较概括性的词。interactive是主要为了体现它是通过交互实现的，想着和其他在一辆车上实现的功能区分一下

你的解释并不能说服我。

2023-04-13 12:38 UTC, chenhuiYu00 commented on rm_referee/src/ui/trigger_change_ui.cpp
> +  {
机器人颜色的判断可以写在 referee.cpp下的  rm_referee::RefereeCmdId::ROBOT_STATUS_CMD 的case里，目前只存了robot_id，目前在这里可以顺便判断一下颜色

2023-04-14 09:28 UTC, NaHCO3bc commented
@qiayuanliao

2023-04-15 07:54 UTC, qiayuanliao requested changes
不要用 string 写 red 和 blue 啊天...你是去哪里学的...

2023-04-15 07:55 UTC, qiayuanliao commented
> @qiayuanliao

有没有一种可能你应该先找 @ye-luo-xi-tui 看过之后再找我

2023-04-15 10:09 UTC, Edwinlinks commented on rm_referee/src/ui/trigger_change_ui.cpp
> +std::string SentryInteractiveTriggerChangeUi::getSentryState(uint8_t mode)
这里的判断为什么不像其他的软件包那样弄成结构体，mode作为类内部成员，分别有个set和get

2023-04-15 13:10 UTC, NaHCO3bc commented
> 不要用 string 写 red 和 blue 啊天...你是去哪里学的...

referee.cpp里的getRobotInfo()是直接用red和blue了，就仿照那里做robot_color_的判断了

2023-04-15 13:11 UTC, NaHCO3bc commented on rm_referee/src/ui/trigger_change_ui.cpp
> +std::string SentryInteractiveTriggerChangeUi::getSentryState(uint8_t mode)
> 这里的判断为什么不像其他的软件包那样弄成结构体，mode作为类内部成员，分别有个set和get

主要其他的trigger ui都是这样做的，就这样写了

2023-04-16 11:14 UTC, Edwinlinks commented on rm_referee/src/ui/trigger_change_ui.cpp
> +  else if (base_.robot_id_ == rm_msgs::GameRobotStatus::BLUE_SENTRY)
这里直接判断是哨兵就返回不就好了

2023-04-16 11:16 UTC, Edwinlinks commented on rm_referee/src/ui/trigger_change_ui.cpp
> +std::string SentryInteractiveTriggerChangeUi::getSentryState(uint8_t mode)
> > 这里的判断为什么不像其他的软件包那样弄成结构体，mode作为类内部成员，分别有个set和get
> 
> 主要其他的trigger ui都是这样做的，就这样写了

那也没有像你这样直接判断0,1呀，你可以参考ShooterTriggerChangeUi

2023-04-16 11:16 UTC, Edwinlinks commented on rm_referee/src/ui/trigger_change_ui.cpp
> +  else if (base_.robot_id_ != rm_msgs::GameRobotStatus::BLUE_SENTRY)
此时同理

2023-04-16 11:18 UTC, Edwinlinks commented on rm_referee/include/rm_referee/ui/trigger_change_ui.h
> +  };
这里为啥是赋成1，2，而不是默认的0，1

2023-04-16 11:22 UTC, Edwinlinks commented on rm_referee/src/referee.cpp
> +          base_.robot_color_ = base_.robot_id_ >= 100 ? "blue" : "red";
你这里是判断自己的颜色？大于100是红色吧，manual那边的判断使用来判断敌方颜色才反着写的呀

2023-04-16 11:30 UTC, Edwinlinks commented
> > 不要用 string 写 red 和 blue 啊天...你是去哪里学的...
> 
> referee.cpp里的getRobotInfo()是直接用red和blue了，就仿照那里做robot_color_的判断了

判断红蓝的方式应该按照廖佬说的“getRobotColor(int robot_id) 直接返回颜色的 enum”，这类方式，你改成这样吧

2023-04-16 11:38 UTC, Edwinlinks commented
> > > 不要用 string 写 red 和 blue 啊天...你是去哪里学的...
> > 
> > 
> > referee.cpp里的getRobotInfo()是直接用red和blue了，就仿照那里做robot_color_的判断了
> 
> 判断红蓝的方式应该按照廖佬说的“getRobotColor(int robot_id) 直接返回颜色的 enum”，这类方式，你改成这样吧

rm_referee的话，应该只有ui部分会用到，解包的那个类用不到这个，我建议可以写在ui的基类里面去

2023-04-16 13:34 UTC, NaHCO3bc commented on rm_referee/src/ui/trigger_change_ui.cpp
> +std::string SentryInteractiveTriggerChangeUi::getSentryState(uint8_t mode)
> > > 这里的判断为什么不像其他的软件包那样弄成结构体，mode作为类内部成员，分别有个set和get
> > 
> > 
> > 主要其他的trigger ui都是这样做的，就这样写了
> 
> 那也没有像你这样直接判断0,1呀，你可以参考ShooterTriggerChangeUi

这样的话就只能在类里面再加枚举了

2023-04-16 17:03 UTC, Edwinlinks commented on rm_referee/src/ui/trigger_change_ui.cpp
> +    return "CRUISE_GYRO";
这里CRUISE_GYRO改成sentry_gryo都好一点，你这个词有点意义不明，“巡航小陀螺”

2023-04-16 17:29 UTC, NaHCO3bc commented on rm_referee/src/ui/trigger_change_ui.cpp
> +    return "CRUISE_GYRO";
> 这里CRUISE_GYRO改成sentry_gryo都好一点，你这个词有点意义不明，“巡航小陀螺”

嘶但是fsm里那个参数就叫cruise_gyro，就想着统一了

2023-04-16 17:30 UTC, Edwinlinks commented on rm_referee/src/ui/trigger_change_ui.cpp
> +    return "CRUISE_GYRO";
> > 这里CRUISE_GYRO改成sentry_gryo都好一点，你这个词有点意义不明，“巡航小陀螺”
> 
> 嘶但是fsm里那个参数就叫cruise_gyro，就想着统一了

那fsm那个也得改改

2023-04-16 18:00 UTC, NaHCO3bc commented on rm_referee/src/ui/trigger_change_ui.cpp
> +    return "CRUISE_GYRO";
> > > 这里CRUISE_GYRO改成sentry_gryo都好一点，你这个词有点意义不明，“巡航小陀螺”
> > 
> > 
> > 嘶但是fsm里那个参数就叫cruise_gyro，就想着统一了
> 
> 那fsm那个也得改改

先改了referee里的了

2023-04-17 06:50 UTC, Edwinlinks commented on rm_referee/include/rm_referee/ui/trigger_change_ui.h
> +      if (i == BLUE_ENGINEER || i == BLUE_AERIAL)
你这样不是工程和空中都会push back吗

2023-04-17 07:04 UTC, NaHCO3bc commented on rm_referee/include/rm_referee/ui/trigger_change_ui.h
> +      if (i == BLUE_ENGINEER || i == BLUE_AERIAL)
> 你这样不是工程和空中都会push back吗

嘶好像应该把判断写在push back前

2023-04-17 07:12 UTC, Edwinlinks commented on rm_referee/include/rm_referee/ui/trigger_change_ui.h
> +      if (i == BLUE_ENGINEER || i == BLUE_AERIAL)
> > 你这样不是工程和空中都会push back吗
> 
> 嘶好像应该把判断写在push back前

你的逻辑就除了空中和工程都push back就行，可以不用continue

2023-04-17 07:24 UTC, NaHCO3bc commented on rm_referee/include/rm_referee/ui/trigger_change_ui.h
> +      if (i == BLUE_ENGINEER || i == BLUE_AERIAL)
> > > 你这样不是工程和空中都会push back吗
> > 
> > 
> > 嘶好像应该把判断写在push back前
> 
> 你的逻辑就除了空中和工程都push back就行，可以不用continue

那continue不是就继续循环，主要是枚举hero到sentry中间就会有工程和空中

2023-04-17 11:18 UTC, Edwinlinks commented on rm_referee/include/rm_referee/ui/trigger_change_ui.h
> +      if (i == BLUE_ENGINEER || i == BLUE_AERIAL)
> > > > 你这样不是工程和空中都会push back吗
> > > 
> > > 
> > > 嘶好像应该把判断写在push back前
> > 
> > 你的逻辑就除了空中和工程都push back就行，可以不用continue
> 
> 那continue不是就继续循环，主要是枚举hero到sentry中间就会有工程和空中

我的意思是，你发现是空中和工程就不push back，其他才push进去，比如
if（不是空中和工程）
  push back

2023-04-17 11:34 UTC, NaHCO3bc commented on rm_referee/include/rm_referee/ui/trigger_change_ui.h
> +      if (i == BLUE_ENGINEER || i == BLUE_AERIAL)
> > > > > 你这样不是工程和空中都会push back吗
> > > > 
> > > > 
> > > > 嘶好像应该把判断写在push back前
> > > 
> > > 
> > > 你的逻辑就除了空中和工程都push back就行，可以不用continue
> > 
> > 
> > 那continue不是就继续循环，主要是枚举hero到sentry中间就会有工程和空中
> 
> 我的意思是，你发现是空中和工程就不push back，其他才push进去，比如 if（不是空中和工程） push back

噢噢噢 get it

2023-04-17 16:35 UTC, Edwinlinks commented
你明天找时间赶紧测试一下吧，看起来没有什么其他问题 @NaHCO3bc

2023-04-17 16:36 UTC, Edwinlinks commented
> 你明天找时间赶紧测试一下吧，看起来没有什么其他问题 @NaHCO3bc

测试一下你现在改好的这版

2023-04-26 14:38 UTC, closed without merging