Write a gpio interface(only read)
rm-controls/rm_control pull request #12
Opened 2021-09-30 06:32 UTC by ye-luo-xi-tui

2021-10-02 17:33 UTC, qiayuanliao commented
增加一个新功能叫  “add” 不叫 write..........

2021-10-02 17:34 UTC, qiayuanliao commented
是 read only 不是 only read

2021-10-02 17:35 UTC, qiayuanliao commented
不要回复我这是抄以前的 gpio manger 的写法，一切以现在的代码规范和标准为准

2021-10-02 17:39 UTC, qiayuanliao requested changes

2021-10-02 17:39 UTC, qiayuanliao commented on rm_hw/include/rm_hw/hardware_interface/gpio_manager.h
> +#define SRC_CHASSIS_BASE_INCLUDE_GPIO_MANAGER_H_
看 code style

2021-10-02 17:39 UTC, qiayuanliao commented on rm_hw/include/rm_hw/hardware_interface/gpio_manager.h
> +  std::map<int, int> mapInputIo_;
参考别的地方怎么命名，这个是很旧版的写法了

2021-10-02 17:39 UTC, qiayuanliao commented on rm_common/include/rm_common/hardware_interface/gpio_state_interface.h
> +  GpioStateHandle(std::string name, int* value) : name_(name), value_(value)
int* value 不应该用int吧？

2021-10-02 17:39 UTC, qiayuanliao commented on rm_hw/include/rm_hw/hardware_interface/hardware_interface.h
> +  bool parseGpioCfg(XmlRpc::XmlRpcValue& gpio_cfgs, ros::NodeHandle& robot_hw_nh);
Cfg 哪里臆想出来的？

2021-10-02 17:39 UTC, qiayuanliao commented on rm_hw/src/hardware_interface/parse.cpp
> +bool RmRobotHW::parseGpioCfg(XmlRpc::XmlRpcValue& gpio_cfgs, ros::NodeHandle& robot_hw_nh)
cfgs 根据哪里这么写的？？？ 这份代码哪里有写过"cfg"？

2021-10-02 17:39 UTC, qiayuanliao commented on rm_common/include/rm_common/hardware_interface/gpio_state_interface.h
> +class GpioStateHandle
不应该叫 `GpioState`, state 是只读不写，虽然说现在只读不写，但是以后肯定即读又写，应该直接叫 `GpioHandle` 和 `GpioInterface`

2021-10-02 17:39 UTC, qiayuanliao commented on rm_hw/src/hardware_interface/gpio_manager.cpp
> +bool GpioMangager::init(const ros::NodeHandle& module_nh)
此处不应该读取 rosparam，所有 参数服务器读取和处理的都应该在写 parse.cpp 中

2021-10-03 15:24 UTC, ye-luo-xi-tui commented on rm_hw/src/hardware_interface/gpio_manager.cpp
> +bool GpioMangager::init(const ros::NodeHandle& module_nh)
其实这个函数并没有用到，也确实在parse.cpp中写了个读取和处理，这个函数是一开始为用在吴老师底盘车灯而写的，就保留了下来

2021-10-03 15:27 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/hardware_interface/gpio_state_interface.h
> +class GpioStateHandle
这个，我打算后面搞个GpioInterface继承GpioState，变成既读又写

2021-10-03 16:13 UTC, ye-luo-xi-tui commented on rm_hw/include/rm_hw/hardware_interface/gpio_manager.h
> +#define SRC_CHASSIS_BASE_INCLUDE_GPIO_MANAGER_H_
是谷歌规范吗

2021-10-04 08:55 UTC, qiayuanliao commented on rm_common/include/rm_common/hardware_interface/gpio_state_interface.h
> +class GpioStateHandle
你看清楚你在说什么？？？？

2021-10-04 08:55 UTC, qiayuanliao commented on rm_common/include/rm_common/hardware_interface/gpio_state_interface.h
> +class GpioStateHandle
什么叫 搞个GpioInterface继承GpioState ????

2021-10-04 08:55 UTC, qiayuanliao commented on rm_hw/include/rm_hw/hardware_interface/gpio_manager.h
> +#define SRC_CHASSIS_BASE_INCLUDE_GPIO_MANAGER_H_
不是

2021-10-04 08:56 UTC, qiayuanliao commented on rm_common/include/rm_common/hardware_interface/gpio_state_interface.h
> +class GpioStateHandle
你看看哪里有这么写过？ 为什么要专门绕这么个继承？

2021-10-04 08:56 UTC, qiayuanliao commented on rm_hw/src/hardware_interface/gpio_manager.cpp
> +bool GpioMangager::init(const ros::NodeHandle& module_nh)
那为什么要保留？

2021-10-04 09:01 UTC, qiayuanliao commented on rm_common/include/rm_common/hardware_interface/gpio_state_interface.h
> +class GpioStateHandle
> 什么叫 搞个GpioInterface继承GpioState ????

你是指搞个 GpioHandle 继承 GpioStateHandle 吗？就像 JointHandle 继承 JointStateHandle 一样？你自己读一下你说了啥乱七八糟的话？我还得慢慢揣摩你的意思

2021-10-05 06:34 UTC, qiayuanliao commented on rm_common/include/rm_common/hardware_interface/gpio_state_interface.h
> +class GpioStateHandle
> 对，就是这个意思。我是看到JointHandle继承JointStateHandle才想这么干的。

想法是对的，表述要准确

2022-01-17 01:47 UTC, qiayuanliao requested changes
有很多与GPIO没有无关的修改

2022-02-11 14:15 UTC, merged