Add Multi_dof_commandsender for Multi_dof_controller.
rm-controls/rm_control pull request #122
Opened 2023-03-27 11:31 UTC by L-SY

已经过实车测试，可以正常使用，参数获取有待考量。

2023-03-28 07:18 UTC, ye-luo-xi-tui approved these changes

2023-03-28 07:19 UTC, ye-luo-xi-tui commented
自行解决合并冲突

2023-03-28 07:46 UTC, L-SY commented
> 自行解决合并冲突

应该解决了

2023-03-28 13:31 UTC, qiayuanliao commented
标题的 code style 是什么鬼

2023-03-28 14:43 UTC, L-SY commented
> 标题的 code style 是什么鬼

以改为首字母大写，无下划线连接的模式。

2023-04-07 05:34 UTC, ljq-lv approved these changes

2023-04-07 14:01 UTC, qiayuanliao requested changes
Twist 的定义就是空间速度，无论在ROS中还是在其他地方（只要是机器人学）。并且将xyz的角速度重命名为 roll pitch yaw （一种姿态的表示方式） 也是错的。

需要修改 rm_msgs/FultiDofCmd，我心中已经有了答案，就看你们能不能想到一起去了 ：)

2023-04-11 00:39 UTC, L-SY commented
> Twist 的定义就是空间速度，无论在ROS中还是在其他地方（只要是机器人学）。并且将xyz的角速度重命名为 roll pitch yaw （一种姿态的表示方式） 也是错的。
> 
> 需要修改 rm_msgs/FultiDofCmd，我心中已经有了答案，就看你们能不能想到一起去了 ：)

学到了，将Twist拆为两个Vector3，用angular_x,angular_y,angular_z代替之前的roll,pitch,yaw。

2023-04-11 16:10 UTC, qiayuanliao commented
> > Twist 的定义就是空间速度，无论在ROS中还是在其他地方（只要是机器人学）。并且将xyz的角速度重命名为 roll pitch yaw （一种姿态的表示方式） 也是错的。
> > 需要修改 rm_msgs/FultiDofCmd，我心中已经有了答案，就看你们能不能想到一起去了 ：)
> 
> 学到了，将Twist拆为两个Vector3，用angular_x,angular_y,angular_z代替之前的roll,pitch,yaw。

"并且将xyz的角速度重命名为 roll pitch yaw （一种姿态的表示方式） 也是错的" 直接把我这句话无视了 = =. 

函数命名要改！改成什么？

2023-04-11 16:25 UTC, L-SY commented
> > > Twist 的定义就是空间速度，无论在ROS中还是在其他地方（只要是机器人学）。并且将xyz的角速度重命名为 roll pitch yaw （一种姿态的表示方式） 也是错的。
> > > 需要修改 rm_msgs/FultiDofCmd，我心中已经有了答案，就看你们能不能想到一起去了 ：)
> > 
> > 
> > 学到了，将Twist拆为两个Vector3，用angular_x,angular_y,angular_z代替之前的roll,pitch,yaw。
> 
> "并且将xyz的角速度重命名为 roll pitch yaw （一种姿态的表示方式） 也是错的" 直接把我这句话无视了 = =.
> 
> 函数命名要改！改成什么？

修改成了setGroupValue()，用angular_x,angular_y,angular_z代替之前的roll,pitch,yaw，把一些多余的函数删除了。

2023-04-13 10:38 UTC, merged