Move the double barrel switcher into command sender from fsm.
rm-controls/rm_control pull request #147
Opened 2023-05-05 17:01 UTC by NaHCO3bc

2023-05-07 08:00 UTC, ye-luo-xi-tui commented
把我提的要求写进描述里

2023-05-07 11:52 UTC, ye-luo-xi-tui requested changes

2023-05-07 11:52 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/decision/command_sender.h
> +    barrel_nh.getParam("off_point", off_point_);
只有弹仓盖才有on off的说法

2023-05-07 11:52 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/decision/command_sender.h
> +    barrel_nh.getParam("off_point", off_point_);
只有弹仓盖才有on off的说法

2023-05-07 11:52 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/decision/command_sender.h
> +class DoubleBarrelSwitcher
它的功能不只是切换，应叫`DoubleBarrelCommandSender`更好

2023-05-07 11:52 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/decision/command_sender.h
> +  }
上次跟你说的很清楚了，ShooterCommandSender没有的公共接口你这个也不应该有！

2023-05-07 11:52 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/decision/command_sender.h
> +  {
不是公共的接口放在private

2023-05-07 11:52 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/decision/command_sender.h
> +  }
同上

2023-05-07 11:52 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/decision/command_sender.h
> +  void sendAutoShooterCmd()
不应该分出auto和manual我想锤死你了都。
ShooterCommandSender需要用到的接口你再写一个函数名一模一样的！

2023-05-11 06:32 UTC, NaHCO3bc commented on rm_common/include/rm_common/decision/command_sender.h
> +  }
> 上次跟你说的很清楚了，ShooterCommandSender没有的公共接口你这个也不应该有！

那这个ShooterCommandSender没有，但我又需要用到

2023-05-11 06:35 UTC, NaHCO3bc commented on rm_common/include/rm_common/decision/command_sender.h
> +  void sendAutoShooterCmd()
> 不应该分出auto和manual我想锤死你了都。 ShooterCommandSender需要用到的接口你再写一个函数名一模一样的！

那之前不是说把双枪切换时的逻辑改到这个类里实现吗，那哨兵自动情况下的sendCommand和手动情况下以及其他机器人的sendCommand怎么区分

2023-05-11 06:37 UTC, NaHCO3bc commented on rm_common/include/rm_common/decision/command_sender.h
> +    barrel_nh.getParam("off_point", off_point_);
> 只有弹仓盖才有on off的说法

改成id1_point,id2_point这样行吗

2023-05-16 02:12 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/decision/command_sender.h
> +#include <rm_msgs/DbusData.h>
不需要

2023-05-16 02:25 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/decision/command_sender.h
> +  void switchBarrel()
719到770行作为private，同时切枪管的逻辑写进sendCommand

2023-05-16 11:43 UTC, NaHCO3bc commented on rm_common/include/rm_common/decision/command_sender.h
> +  void switchBarrel()
> 719到770行作为private，同时切枪管的逻辑写进sendCommand

现在留在public的都是fsm会调用的，其他的都移到private了；另外已经将切枪管逻辑移到sendCommand里了，在仿真里测过了

2023-05-16 17:25 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/decision/command_sender.h
> +        shooter_ID2_cooling_limit - shooter_ID2_cooling_heat < 30)
"30"应参数化

2023-05-16 18:18 UTC, ye-luo-xi-tui commented
ci没过，`pre-commit install`！

2023-05-17 09:07 UTC, NaHCO3bc commented on rm_common/include/rm_common/decision/command_sender.h
> +        return shooter_ID1_cooling_limit - shooter_ID1_cooling_heat < 30;
> 此处切枪的判断条件存在bug，如果两根枪管剩余热量都小于30，是不是就一直切枪直到有一根冷却小于30了？我提供一个思路，另一根枪管的剩余热量减当前枪管的大于某个值（一个可调的参数）才切枪管。

两个枪管都小于30的情况下，会一直维持在当前枪管，直到另外一根枪管冷却到剩余热量大于30的时候再切换。
这样其实就是在冷却速率不高的情况下，会两根都快打满的时候就打几颗就切。
你的这个思路其实就是延长在当前枪管的时间，让另外一根枪管冷却多一些时间再切换来打，就是这延长的时间就比较长

2023-05-17 09:07 UTC, NaHCO3bc commented
> ci没过，`pre-commit install`！

怪 这我真配了

2023-05-18 06:50 UTC, NaHCO3bc commented on rm_common/include/rm_common/decision/command_sender.h
> +        return shooter_ID1_cooling_limit - shooter_ID1_cooling_heat < 30;
按照你的思路添加了一个判断条件来切枪管，在仿真中测试是可以实现所期待功能。但没在实车上测试，不清楚具体实现效果

2023-06-20 17:13 UTC, Edwinlinks commented on rm_common/include/rm_common/decision/command_sender.h
> +    shooter_ID2_cmd_sender_->checkError(time);
你这里不应该是哪个枪管就调用哪个的checkError吗

2023-06-20 17:20 UTC, Edwinlinks commented on rm_common/include/rm_common/decision/command_sender.h
> +    shooter_ID2_cmd_sender_->checkError(time);
这个类里面应该是只更新裁判系统的数据吧，像是拿到射频或者checkError这种应该当前是哪个枪管就调哪一个才对

2023-06-20 17:32 UTC, Edwinlinks commented on rm_common/include/rm_common/decision/command_sender.h
> +    shooter_ID2_cmd_sender_->checkError(time);
> 这个类里面应该是只更新裁判系统的数据吧，像是拿到射频或者checkError这种应该当前是哪个枪管就调哪一个才对

shooter controller只有一个，你两个command sender肯定topic都是同一个，你现在的写法没考虑到这一点，这个函数的同类函数也是，改动过后有测过吗？

2023-06-25 11:00 UTC, NaHCO3bc commented on rm_common/include/rm_common/decision/command_sender.h
> +    shooter_ID2_cmd_sender_->checkError(time);
> > 这个类里面应该是只更新裁判系统的数据吧，像是拿到射频或者checkError这种应该当前是哪个枪管就调哪一个才对
> 
> shooter controller只有一个，你两个command sender肯定topic都是同一个，你现在的写法没考虑到这一点，这个函数的同类函数也是，改动过后有测过吗？

这两个cmd sender在构造的时候已经是把topic写成同一个了，所有类似的函数只是让这两个cmdsender在sendcommand的时候内容一致

2023-06-25 16:27 UTC, ye-luo-xi-tui commented
合并ddl：6.30

2023-06-28 08:55 UTC, Edwinlinks commented on rm_common/include/rm_common/decision/command_sender.h
> +    shooter_ID2_cmd_sender_->checkError(time);
> > > 这个类里面应该是只更新裁判系统的数据吧，像是拿到射频或者checkError这种应该当前是哪个枪管就调哪一个才对
> > 
> > 
> > shooter controller只有一个，你两个command sender肯定topic都是同一个，你现在的写法没考虑到这一点，这个函数的同类函数也是，改动过后有测过吗？
> 
> 这两个cmd sender在构造的时候已经是把topic写成同一个了，所有类似的函数只是让这两个cmdsender在sendcommand的时候内容一致

我知道，我的意思是“像是拿到射频或者checkError这种应该当前是哪个枪管就调哪一个才对”！而不是摆烂的所有都checkError一次，你不觉得这样子不好吗

2023-07-03 13:48 UTC, merged