Modify ShootCmd add the function of adjusting the speed in the shooter command sender
rm-controls/rm_control pull request #188
Opened 2023-07-29 07:48 UTC by 1moule

将期望的转速值加入ShootCmd中，并在shooter commander中实现调整摩擦轮转速的功能

2023-07-29 17:09 UTC, ye-luo-xi-tui approved these changes

2023-07-29 17:14 UTC, ye-luo-xi-tui commented
ddl 7.30

2023-07-30 16:31 UTC, qiayuanliao requested changes
另外 rm_msgs 里面的 ExtraFrictionWheelSpeed 要删掉。

改完之后叶子哥确定都改了，就直接merge，不需要再次 review 了~

2023-07-30 16:31 UTC, qiayuanliao commented on rm_msgs/msg/ShootCmd.msg
> +float64 qd_des
改为 wheel_speed, 其他发射相关代码的 "qd" "rotate_speed" 也都改为 wheel_speed。

记得改控制器，你可以用全局搜索，找 “qd” 和 "rotat" 字样。

这是历史遗留问题，不是你的问题，这次顺便改了。

2023-08-02 10:39 UTC, merged