Complete multiple actuators transmission
rm-controls/rm_control pull request #25
Opened 2021-12-30 11:31 UTC by Edwinlinks

2021-12-30 16:54 UTC, qiayuanliao commented
@ye-luo-xi-tui 根据官方的 transmission 和我们的双执行器 transmission 对本 pr 进行 review

2022-01-03 12:25 UTC, qiayuanliao commented
Commit message 需修改， double actuator 可以删掉

2022-03-10 17:50 UTC, Edwinlinks commented
已修改commit信息并且删去了double actuator

2022-03-11 05:29 UTC, qiayuanliao requested changes
Pre-commit 没过！！！把你的环境配好！！！不要再出现这种情况了。。。。。。。。。。

2022-03-12 18:22 UTC, qiayuanliao commented
CI 没过！！！！！！！！！！！！！！自己主动修！！！！！！！！！！！

2022-03-13 06:06 UTC, Edwinlinks commented
好的，我在找没过的原因，尽快修

2022-04-03 05:13 UTC, qiayuanliao commented
@Edwinlinks

2022-04-04 11:09 UTC, qiayuanliao commented
@Edwinlinks

2022-04-06 17:26 UTC, closed without merging