Completed tof_sensor_interface
rm-controls/rm_control pull request #29
Opened 2022-01-18 16:19 UTC by Edwinlinks

2022-01-18 20:46 UTC, ye-luo-xi-tui commented
没有大问题，你看看吧 @qiayuanliao

2022-01-21 13:45 UTC, qiayuanliao requested changes
做得很好，Code style 有被很好注意。
唯一不足的：头文件的引用顺序还有各种函数的顺序需要按照重要程度排列，方便阅读。

2022-01-21 13:45 UTC, qiayuanliao commented on rm_msgs/msg/TofSensor.msg
> +float64 dis_status
为什么是float64，应该是 int 吧？
而且应该用uint8声明清楚各种状态的值（例子见：ChassisCmd.msg 和 GimbalCmd.msg 等）。
并思考为什么要这样做，如果你想不出来，去查看 rm_manual 的指令发送，并回复我

2022-01-21 13:45 UTC, qiayuanliao commented on rm_hw/include/rm_hw/hardware_interface/hardware_interface.h
> +#include <rm_common/hardware_interface/tof_sensor_interface.h>
你的TOF很重要吗？凭什么放在电机等 interface 前面？

2022-01-21 13:45 UTC, qiayuanliao commented
> 没有大问题，你看看吧 @qiayuanliao

看一下我的review，以后注意一下

2022-03-10 17:10 UTC, Edwinlinks commented on rm_hw/include/rm_hw/hardware_interface/hardware_interface.h
> +#include <rm_common/hardware_interface/tof_sensor_interface.h>
已修改头文件的位置，参考hardware_interface.h中imu_extra_interface.h的位置

2022-03-10 17:10 UTC, Edwinlinks commented on rm_msgs/msg/TofSensor.msg
> +float64 dis_status
我的理解是：使用uint8作为状态值是因为用于发送指令的枚举变量的类型是int
已经修改dis_status的数据类型，但是对于distance我没有理解为什么应该用int，我暂时觉得float64适合这个值

2022-03-10 17:11 UTC, qiayuanliao commented on rm_hw/src/hardware_interface/can_bus.cpp
> +          ((uint32_t)(((uint32_t)frame.data[2]) << 16) | ((uint32_t)frame.data[1] << 8) | (uint32_t)frame.data[0]) /
括号确定了吗

2022-03-10 17:41 UTC, Edwinlinks commented on rm_hw/src/hardware_interface/can_bus.cpp
> +          ((uint32_t)(((uint32_t)frame.data[2]) << 16) | ((uint32_t)frame.data[1] << 8) | (uint32_t)frame.data[0]) /
还没确认，我明天确认后将会回复，在确定括号内容不需要后我会删去并再次commit

2022-03-11 01:58 UTC, qiayuanliao commented on rm_hw/src/hardware_interface/can_bus.cpp
> +          ((uint32_t)(((uint32_t)frame.data[2]) << 16) | ((uint32_t)frame.data[1] << 8) | (uint32_t)frame.data[0]) /
我现先merge了 后面开新pr

2022-03-11 01:58 UTC, merged