Add doxygen comments on hardware_interface.h
rm-controls/rm_control pull request #4
Opened 2021-08-21 15:31 UTC by ye-luo-xi-tui

2021-08-21 15:41 UTC, qiayuanliao requested changes
你的所有注释都是只有 \brief ？？？

2021-08-21 16:40 UTC, ye-luo-xi-tui commented
> 你的所有注释都是只有 \brief ？？？

只有\brief是什么意思，不是有param和return吗

2021-08-21 16:43 UTC, qiayuanliao commented
> > 你的所有注释都是只有 \brief ？？？
> 
> 只有\brief是什么意思，不是有param和return吗

你看例子去，自己看少了啥

2021-08-21 16:59 UTC, ye-luo-xi-tui commented
> > > 你的所有注释都是只有 \brief ？？？
> > 
> > 
> > 只有\brief是什么意思，不是有param和return吗
> 
> 你看例子去，自己看少了啥

你的例子是指ros_best_practices吗？param和return都写了，包括你在群上发的图片我也找不到还缺啥。

2021-08-22 07:49 UTC, qiayuanliao requested changes
提到其他函数应该用引用（ref）而不是直接说它的函数名

2021-08-23 12:23 UTC, qiayuanliao approved these changes

2021-08-23 12:23 UTC, merged