Add imu angular_vel_offset.
rm-controls/rm_control pull request #46
Opened 2022-05-19 13:49 UTC by XYM-github

Add imu angular_vel_offset.

2022-05-20 08:58 UTC, ye-luo-xi-tui commented
@qiayuanliao

2022-05-22 16:19 UTC, qiayuanliao requested changes

2022-05-22 16:19 UTC, qiayuanliao commented on rm_hw/src/hardware_interface/parse.cpp
> +      }
放在幅值的代码附近好点？

2022-05-23 15:02 UTC, ye-luo-xi-tui commented
@XYM-github

2022-05-24 14:38 UTC, qiayuanliao commented
@XYM-github

2022-05-26 10:31 UTC, qiayuanliao commented
@XYM-github CI 没过哦

2022-05-26 10:31 UTC, qiayuanliao commented
@XYM-github CI 没过哦

2022-05-28 13:26 UTC, qiayuanliao approved these changes

2022-05-28 13:26 UTC, merged