Complete the referee part of manual separation.
rm-controls/rm_control pull request #70
Opened 2022-07-27 09:24 UTC by chenhuiYu00

2022-07-27 10:03 UTC, ye-luo-xi-tui commented on rm_referee/include/rm_referee/engineer_referee.h
> +  bool symbol;
类成员变量下划线作后缀，好好检查一遍

2022-07-27 10:03 UTC, ye-luo-xi-tui commented on rm_referee/include/rm_referee/radar_referee.h
> +  std::vector<int> blue_receiver = {
同上

2022-07-27 10:04 UTC, ye-luo-xi-tui commented on rm_referee/include/rm_referee/referee/data.h
> +  bool is_online_ = false;
结构体成员不需要下划线

2022-07-27 13:21 UTC, ye-luo-xi-tui approved these changes

2022-07-27 14:35 UTC, Edwinlinks commented on rm_common/include/rm_common/decision/heat_limit.h
> +
这部分不应该这么改，应该用一个函数来传这些要用到的裁判系统数据的指针来对，而不是用三个函数去更新数据

2022-07-27 14:35 UTC, Edwinlinks commented on rm_common/include/rm_common/decision/power_limit.h
> +  }
这部分也是同上

2022-07-28 02:02 UTC, Edwinlinks commented on rm_common/include/rm_common/decision/power_limit.h
> +    if (robot_id_ == rm_referee::RobotId::BLUE_SENTRY || robot_id_ == rm_referee::RobotId::RED_SENTRY)
这部分直接改成用数字判断机器人种类吧？怎么能在 rm_common 里面包含 rm_referee 的头文件呢。

2022-07-28 02:06 UTC, Edwinlinks commented on rm_common/CMakeLists.txt
> +
上述的问题改了之后，把这里删了。

2022-07-28 02:09 UTC, Edwinlinks commented on rm_common/include/rm_common/decision/power_limit.h
> +    else if (robot_id_ == rm_referee::RobotId::RED_ENGINEER || robot_id_ == rm_referee::RobotId::BLUE_ENGINEER)
这里同上

2022-07-28 02:09 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/decision/power_limit.h
> +    if (robot_id_ == rm_referee::RobotId::BLUE_SENTRY || robot_id_ == rm_referee::RobotId::RED_SENTRY)
额，用数字怎么表示颜色？（话说原来的代码里为什么需要知道颜色）据说晨辉给廖洽源解释了这种情况，而后者坚持把RobotId放在rm_referee

2022-07-28 02:16 UTC, Edwinlinks commented on rm_common/include/rm_common/decision/power_limit.h
> +    if (robot_id_ == rm_referee::RobotId::BLUE_SENTRY || robot_id_ == rm_referee::RobotId::RED_SENTRY)
裁判系统串口协议手册中有写，不同颜色是有对应的 id 表示的，这里是为了判断是哨兵。

2022-07-28 02:29 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/decision/power_limit.h
> +    if (robot_id_ == rm_referee::RobotId::BLUE_SENTRY || robot_id_ == rm_referee::RobotId::RED_SENTRY)
> 裁判系统串口协议手册中有写，不同颜色是有对应的 id 表示的，这里是为了判断是哨兵。

是哦，这里robot_id是int类型，但是数字没有枚举值那么直截了当地知道是哨兵，而且万一后面裁判系统协议改了，这部分代码也要跟着改。

2022-07-28 07:24 UTC, qiayuanliao commented on rm_common/include/rm_common/decision/power_limit.h
> +    if (robot_id_ == rm_referee::RobotId::BLUE_SENTRY || robot_id_ == rm_referee::RobotId::RED_SENTRY)
rm_common 里面不可能有 rm_referee 依赖，这个PowerLimit 接收的是topic的数据，应该直接使用 rm_msgs （如果里面没有枚举，应该在 .msg 里面写）来判断。

2022-07-28 07:24 UTC, qiayuanliao commented on rm_common/include/rm_common/decision/power_limit.h
> +    if (robot_id_ == rm_referee::RobotId::BLUE_SENTRY || robot_id_ == rm_referee::RobotId::RED_SENTRY)
rm_common 只有 rm_msgs 作为依赖，不可能有别的自己的包了！

2022-07-28 08:19 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/decision/power_limit.h
> +  }
@chenhuiYu00 `rm_msgs::GameStatus`貌似有robot_id，这个貌似不需要？

2022-07-28 08:19 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/decision/power_limit.h
> +  }
然后直接不需要依赖rm_referee

2022-07-29 13:53 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/decision/power_limit.h
> +    if (game_robot_status_->robot_id == 107 || game_robot_status_->robot_id == 7)
加个是哨兵的注释吧

2022-07-29 13:53 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/decision/power_limit.h
> +    else if (game_robot_status_->robot_id == 102 || game_robot_status_->robot_id == 2)
同

2022-07-29 13:58 UTC, ye-luo-xi-tui commented on rm_referee/include/rm_referee/common/data.h
> +};
似乎已经不存在data类了？

2022-07-29 14:00 UTC, ye-luo-xi-tui reviewed
@ljq-lv @Edwinlinks 看起来还行，帮我看看，救命啊！

2022-07-30 01:24 UTC, Edwinlinks commented on rm_common/include/rm_common/decision/power_limit.h
> +    if (game_robot_status_->robot_id == 107 || game_robot_status_->robot_id == 7)
这里还是没改对呀，上面不是说了如果里面没有枚举，应该在 .msg 里面写吗。

2022-07-30 01:25 UTC, Edwinlinks commented on rm_common/include/rm_common/decision/power_limit.h
> +    if (game_robot_status_->robot_id == 107 || game_robot_status_->robot_id == 7)
这里还是没改对呀，上面不是说了如果里面没有枚举，应该在 .msg 里面写吗。

2022-07-30 01:26 UTC, Edwinlinks commented on rm_common/include/rm_common/decision/power_limit.h
> +    else if (game_robot_status_->robot_id == 102 || game_robot_status_->robot_id == 2)
同上

2022-07-30 01:40 UTC, Edwinlinks commented on rm_common/include/rm_common/decision/power_limit.h
> +    : chassis_cmd_(chassis_cmd)
这里也没按我的要求改，我说了是用一个成员函数来传值。heat_limit也是。

2022-07-30 02:22 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/decision/power_limit.h
> +    : chassis_cmd_(chassis_cmd)
> 这里也没按我的要求改，我说了是用一个成员函数来传值。heat_limit也是。

能用构造函数传的为啥要用一个成员函数呢？

2022-07-30 07:44 UTC, Edwinlinks commented on rm_common/include/rm_common/decision/power_limit.h
> +    : chassis_cmd_(chassis_cmd)
> > 这里也没按我的要求改，我说了是用一个成员函数来传值。heat_limit也是。
> 
> 能用构造函数传的为啥要用一个成员函数呢？

我的想法是只改heat_limit和power_limit 这两个类，通过成员函数传值给这两个类的成员变量。不需要去修改 command_sender。而且真要在构造函数中传值，那肯定是传引用比较好，而不是还在构造那里赋值。

2022-07-30 07:53 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/decision/power_limit.h
> +    : chassis_cmd_(chassis_cmd)
> > > 这里也没按我的要求改，我说了是用一个成员函数来传值。heat_limit也是。
> > 
> > 
> > 能用构造函数传的为啥要用一个成员函数呢？
> 
> 我的想法是只改heat_limit和power_limit 这两个类，通过成员函数传值给这两个类的成员变量。不需要去修改 command_sender。而且真要在构造函数中传值，那肯定是传引用比较好，而不是还在构造那里赋值。

通过成员函数传值是指传引用吗？
那不是一样要修改`command_sender`，不然在哪里调用你这个成员函数。
而且构造函数不是已经被改了吗，那`command_sender`必须要改吧。

2022-07-30 07:53 UTC, Edwinlinks commented on rm_referee/include/rm_referee/common/data.h
> +};
这个类在这没有意义吧，应该删去。

2022-07-30 07:57 UTC, Edwinlinks commented on rm_common/include/rm_common/decision/power_limit.h
> +    : chassis_cmd_(chassis_cmd)
也行吧，但是我觉得按我说的方式改构造函数的传值方式好一点。

2022-07-30 08:00 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/decision/power_limit.h
> +    : chassis_cmd_(chassis_cmd)
> 也行吧，但是我觉得按我说的方式改构造函数的传值方式好一点。

其实引用的底层实现就是指针，觉得引用更安全的话那就引用吧

2022-07-30 08:03 UTC, ljq-lv commented on rm_msgs/msg/referee/RadarData.mag
> +uint8 robot_id
文件名错了

2022-07-30 08:04 UTC, ljq-lv commented on rm_referee/src/engineer_referee.cpp
> +}  // namespace rm_referee
这里逻辑改一下  symbol可以删掉 变成检查step name是否发生改变，然后检测到发生改变了就update

2022-07-30 08:04 UTC, Edwinlinks commented on rm_common/include/rm_common/decision/power_limit.h
> +    : chassis_cmd_(chassis_cmd)
> > 也行吧，但是我觉得按我说的方式改构造函数的传值方式好一点。
> 
> 其实引用的底层实现就是指针，觉得引用更安全的话那就引用吧

主要还是觉得在构造函数那里直接写给变量赋值看起来不太好，我们的其他代码也没有这样的。

2022-07-30 08:08 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/decision/power_limit.h
> +    : chassis_cmd_(chassis_cmd)
> > > 也行吧，但是我觉得按我说的方式改构造函数的传值方式好一点。
> > 
> > 
> > 其实引用的底层实现就是指针，觉得引用更安全的话那就引用吧
> 
> 主要还是觉得在构造函数那里直接写给变量赋值看起来不太好，我们的其他代码也没有这样的。

原代码就是这样的啊，，你不会不知道构造函数后面跟个冒号然后`xx(xx)`的含义吧。

2022-07-30 08:11 UTC, Edwinlinks commented on rm_common/include/rm_common/decision/power_limit.h
> +    : chassis_cmd_(chassis_cmd)
> > > > 也行吧，但是我觉得按我说的方式改构造函数的传值方式好一点。
> > > 
> > > 
> > > 其实引用的底层实现就是指针，觉得引用更安全的话那就引用吧
> > 
> > 
> > 主要还是觉得在构造函数那里直接写给变量赋值看起来不太好，我们的其他代码也没有这样的。
> 
> 原代码就是这样的啊，，你不会不知道构造函数后面跟个冒号然后`xx(xx)`的含义吧。
我说的就是在要改成在后面跟个冒号然后xx(xx)，你都没认真看我说的话。

2022-07-30 08:13 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/decision/power_limit.h
> +    : chassis_cmd_(chassis_cmd)
> > > > > 也行吧，但是我觉得按我说的方式改构造函数的传值方式好一点。
> > > > 
> > > > 
> > > > 其实引用的底层实现就是指针，觉得引用更安全的话那就引用吧
> > > 
> > > 
> > > 主要还是觉得在构造函数那里直接写给变量赋值看起来不太好，我们的其他代码也没有这样的。
> > 
> > 
> > 原代码就是这样的啊，，你不会不知道构造函数后面跟个冒号然后`xx(xx)`的含义吧。
> > 我说的就是在要改成在后面跟个冒号然后xx(xx)，你都没认真看我说的话。

那跟它是引用还是指针没啥关系的

2022-08-02 08:05 UTC, ye-luo-xi-tui commented on rm_referee/src/engineer_referee.cpp
> +}  // namespace rm_referee
@chenhuiYu00 速

2022-08-03 08:21 UTC, Edwinlinks commented on rm_common/include/rm_common/decision/power_limit.h
> +    if (game_robot_status_.robot_id == 107 || game_robot_status_.robot_id == 7)  // Sentry ID
此处仍未修改正确。

2022-08-09 04:53 UTC, Edwinlinks commented on rm_common/include/rm_common/decision/power_limit.h
> +             game_robot_status_.robot_id == RobotId::RED_ENGINEER)  // Engineer ID
这部分怎么还是不按照要求改，我说了是按照 “如果里面没有枚举，应该在 .msg 里面写” 这个评论的要求来改，你为什么还要在下面加个枚举？

2022-08-09 04:56 UTC, Edwinlinks commented on rm_referee/include/rm_referee/referee/data.h
> +#include <rm_referee/referee/protocol.h>
这里应该使用双引号。

2022-08-09 04:57 UTC, Edwinlinks commented on rm_referee/include/rm_referee/referee/referee.h
> +#include <rm_referee/common/referee_base.h>
同上

2022-08-09 04:58 UTC, Edwinlinks commented on rm_referee/include/rm_referee/referee/ui.h
> +#include <rm_msgs/StatusChangeRequest.h>
双引号和双引号放一起，尖括号和尖括号放一起，归一下类。

2022-08-09 05:07 UTC, Edwinlinks commented on rm_referee/src/referee/graph.cpp
> +    config_.end_angle_ = (int)(title_ + content_).size();
这里应该使用 static_cast<int>()，而不是 int()，避免C风格的使用。

2022-08-09 05:08 UTC, Edwinlinks commented on rm_referee/src/referee/graph.cpp
> +    config_.end_angle_ = (int)(title_ + content_).size();
这里也是同上。

2022-08-09 05:15 UTC, Edwinlinks commented on rm_referee/src/referee/graph.cpp
> +      if (i < (int)ui_queue_.back().second.size())
这里的 int() 也要改。

2022-08-31 09:18 UTC, ye-luo-xi-tui approved these changes

2022-08-31 09:23 UTC, ye-luo-xi-tui approved these changes

2022-08-31 12:01 UTC, Edwinlinks commented on rm_referee/CMakeLists.txt
> +
这一段重复了，前面有 ALL_SOURCES 了，为什么不在里面补全，这里的 include 也应该删去。

2022-09-02 12:56 UTC, Edwinlinks approved these changes

2022-09-03 04:05 UTC, qiayuanliao requested changes
配置文件不应该在这个包里面吧？

2022-09-22 03:23 UTC, qiayuanliao approved these changes

2022-09-22 08:49 UTC, ye-luo-xi-tui approved these changes

2022-09-22 08:49 UTC, merged