Add power buffer to power limit.
rm-controls/rm_control pull request #73
Opened 2022-08-31 10:18 UTC by 1moule

2022-08-31 13:14 UTC, ye-luo-xi-tui commented
有没有测试过，效果怎么样

2022-09-02 10:10 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/decision/power_limit.h
> +  double power_coeff_{};
大体上没问题，感觉变量名字需要改。`power_buffer_effor` `power_buffer_offset`实际上是能量，是energy，power是功率。

2022-09-02 12:17 UTC, ye-luo-xi-tui approved these changes

2022-09-02 17:58 UTC, qiayuanliao commented on rm_common/include/rm_common/decision/power_limit.h
> +  double power_coeff_{};
> 大体上没问题，感觉变量名字需要改。`power_buffer_effor` `power_buffer_offset`实际上是能量，是energy，power是功率。

你说的好有道理，但是我只看代码想不到这个解释，刚刚一直没懂为什么叫energy哈哈哈。其实叫 `power_gain` （量纲是 功率/能量 ）和  `buffer_threshold` 可能好一点。

2022-09-02 17:59 UTC, qiayuanliao requested changes

2022-09-02 17:59 UTC, qiayuanliao commented on rm_common/include/rm_common/decision/power_limit.h
>    double burst_power_{};
意思相近的变量，有强关联的变量，可以写在同一行

2022-09-10 08:24 UTC, merged