Check the modification of command sender.
rm-controls/rm_control pull request #78
Opened 2022-10-03 09:30 UTC by chenhuiYu00

2022-10-07 07:59 UTC, Edwinlinks commented on rm_common/include/rm_common/decision/command_sender.h
> +  }
这里的setCoolingRateOf17mmShooter可以合成一个函数吧，毕竟都是在一个msg里面的，没必要搞这么多。

2022-10-07 08:14 UTC, Edwinlinks commented on rm_common/include/rm_common/decision/command_sender.h
> +  virtual void powerHeatDataCallback(const rm_msgs::PowerHeatData::ConstPtr& data);
这里理解错了呀，像是 trackCallback 这种只有gimbal_cmd_sender 会用的不该放在父类里面重载，有共同之处但是会在不同子类特殊化的函数才应该重载。

2022-10-07 08:33 UTC, Edwinlinks commented on rm_common/include/rm_common/decision/command_sender.h
> +  }
像是用到 joint state 这种，sg类型的应该不需要这样改，主要目的还是改裁判系统相关的msg，JointPointCommandSender和JointJogCommandSender的作用都不是为了处理消息。

2022-10-11 17:15 UTC, Edwinlinks commented on rm_common/include/rm_common/decision/command_sender.h
> +  void powerHeatDataCallback(const rm_msgs::PowerHeatData::ConstPtr& data) override
像是这种直接传消息就行了，不用拆开，群里说把消息拆开的目的是假如有两个接口都用到同一个消息这样的情况才拆开。

2022-10-12 12:26 UTC, Edwinlinks commented on rm_common/include/rm_common/decision/command_sender.h
> +  }
为啥要把 gimbal_des_error_ 写在这里面？

2022-10-12 12:28 UTC, Edwinlinks commented on rm_common/include/rm_common/decision/command_sender.h
> +  }
这里这个getJointState()完全是不需要的呀，你的joint_state_都是在manual那里传过来的，你还在这弄个getJointState干什么？

2022-10-12 12:56 UTC, Edwinlinks commented on rm_common/include/rm_common/decision/power_limit.h
> +  float cap_power_;
为啥其他这里是float而不是double？

2022-10-12 17:32 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/decision/command_sender.h
> +  }
应该是joint_state_controller发的，不过确实是莫名其妙

2022-10-12 17:40 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/decision/command_sender.h
> +  int robot_id_, chassis_power_;
chassis_power是干嘛用的？

2022-10-12 17:46 UTC, ye-luo-xi-tui commented
我还是没有看到注册回调函数的地方在哪里，你也从来没有解释

2022-10-13 00:29 UTC, chenhuiYu00 commented on rm_common/include/rm_common/decision/power_limit.h
> +  float cap_power_;
> 



> 我还是没有看到注册回调函数的地方在哪里，你也从来没有解释

这些函数是在manual的回调里面调用的，和referee里UI的的那些回调一样

2022-10-13 09:35 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/decision/command_sender.h
> +  void powerHeatDataCallback(const rm_msgs::PowerHeatData::ConstPtr& data) override
啥意思捏

2022-10-13 09:38 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/decision/command_sender.h
> +  rm_msgs::GimbalDesError gimbal_des_error_;
意义不明，到头来manual那边还是要调用checkError来获取gimbal_des_error

2022-10-13 09:57 UTC, chenhuiYu00 commented on rm_common/include/rm_common/decision/power_limit.h
> +  float cap_power_;
> 为啥其他这里是float而不是double？

我看见msg文件里就是定义成float的，所以以float类型储存

2022-10-13 09:59 UTC, chenhuiYu00 commented on rm_common/include/rm_common/decision/command_sender.h
> +  int robot_id_, chassis_power_;
> chassis_power是干嘛用的？

manual有些函数要这个参数，就让chassiscommandsender代存

2022-10-13 11:43 UTC, Edwinlinks commented on rm_common/include/rm_common/decision/power_limit.h
> +  float cap_power_;
> > 
> 
> > 我还是没有看到注册回调函数的地方在哪里，你也从来没有解释
> 
> 这些函数是在manual的回调里面调用的，和referee里UI的的那些回调一样

这些你上次不是说在manual里面注册的吗？

2022-10-14 16:32 UTC, ye-luo-xi-tui commented on rm_common/include/rm_common/decision/command_sender.h
> +  rm_msgs::GimbalDesError gimbal_des_error_;
又说删掉了？

2022-10-15 08:24 UTC, Aung-xiao approved these changes

2022-10-15 08:30 UTC, ye-luo-xi-tui commented
从pr标题什么都看不出来，改一下标题加上适当的描述

2022-10-15 08:30 UTC, ye-luo-xi-tui approved these changes

2022-10-16 08:45 UTC, NaHCO3bc approved these changes

2022-10-16 11:46 UTC, caijiefeng approved these changes

2022-10-17 09:04 UTC, Aung-xiao approved these changes

2022-10-17 16:53 UTC, ye-luo-xi-tui approved these changes

2022-10-18 01:27 UTC, qiayuanliao requested changes

2022-10-18 01:27 UTC, qiayuanliao commented on rm_common/include/rm_common/decision/heat_limit.h
> +      shooter_id_1_42_mm_speed_limit_;
有必要存这么多吗

2022-10-18 01:27 UTC, qiayuanliao commented on rm_common/include/rm_common/decision/heat_limit.h
> +    shooter_id_1_42_mm_speed_limit_ = data.shooter_id_1_42_mm_speed_limit;
不要无脑存

2022-10-18 01:27 UTC, qiayuanliao commented on rm_common/include/rm_common/decision/heat_limit.h
> +      shooter_id_1_42_mm_speed_limit_;
可以在配置文件或者裁判系统数据知道需要拿的cooling limit是哪根枪管的吧

2022-10-18 01:27 UTC, qiayuanliao commented on rm_common/include/rm_common/decision/power_limit.h
>    double getLimitPower()
在这里传 chassis_cmd 引用，而不是在构造函数

2022-10-18 01:27 UTC, qiayuanliao commented on rm_referee/include/rm_referee/common/data.h
这个文件是干嘛的

2022-10-18 01:27 UTC, qiayuanliao commented on rm_referee/include/rm_referee/common/data.h
为啥还是要把所有消息存下来

2022-10-18 01:27 UTC, qiayuanliao commented on rm_referee/include/rm_referee/common/data.h
@ye-luo-xi-tui @Edwinlinks 重点关照一下

2022-10-18 03:00 UTC, chenhuiYu00 commented on rm_common/include/rm_common/decision/heat_limit.h
> +      shooter_id_1_42_mm_speed_limit_;
> 有必要存这么多吗

我想的是如果以后有双枪步兵，只有一个cooling limit就无法描述两根枪管。如果现在是只有一根枪管的机器人的话确实存一根枪管就够了。

2022-10-18 03:02 UTC, chenhuiYu00 commented on rm_referee/include/rm_referee/common/data.h
> 这个文件是干嘛的

存数据和CRC校验代码

2022-10-18 03:03 UTC, chenhuiYu00 commented on rm_referee/include/rm_referee/common/data.h
> 为啥还是要把所有消息存下来

现在要删了，目前是骏骐在改

2022-10-18 03:04 UTC, qiayuanliao commented on rm_referee/include/rm_referee/common/data.h
我肯定知道是存数据的啊。我的意思就是为什么还需要存数据？收到裁判系统数据时往外发不就可以了嘛？为什么需要存下来，是给UI用吗？

2022-10-18 03:06 UTC, chenhuiYu00 commented on rm_referee/include/rm_referee/common/data.h
> 我肯定知道是存数据的啊。我的意思就是为什么还需要存数据？收到裁判系统数据时往外发不就可以了嘛？为什么需要存下来，是给UI用吗？

现在是全存了，修改后只存一小部分数据

2022-10-18 03:07 UTC, qiayuanliao commented on rm_referee/include/rm_referee/common/data.h
懂了，修改 referee 是其他 pr 干的事情

2022-10-18 03:08 UTC, qiayuanliao commented on rm_common/include/rm_common/decision/heat_limit.h
> +      shooter_id_1_42_mm_speed_limit_;
双枪步兵很明显要有两个 shooter sender 实例，也就是分别两个 heat limit 实例。对于每个 heat limit 来说，只有一个 cooling limit

2022-10-19 09:29 UTC, chenhuiYu00 commented on rm_common/include/rm_common/decision/power_limit.h
>    double getLimitPower()
> 在这里传 chassis_cmd 引用，而不是在构造函数

是新建一个函数像setRefereeStatus(bool status)一样作为接口更新chassis_cmd吗？

2022-10-22 11:47 UTC, Aung-xiao approved these changes

2022-10-25 02:47 UTC, qiayuanliao requested changes

2022-10-25 02:47 UTC, qiayuanliao commented on rm_common/include/rm_common/decision/power_limit.h
> +  double getLimitPower(const rm_msgs::ChassisCmd& chassis_cmd_)
莫名而奇妙，甚至code style 都不对

2022-10-25 02:47 UTC, qiayuanliao commented on rm_common/include/rm_common/decision/power_limit.h
> +  double getLimitPower(const rm_msgs::ChassisCmd& chassis_cmd_)
我再把我微信的话原原本本复制一遍：

> 一个函数，它的输出方式是靠 “访问和修改这个函数的某个参数（这个参数是某个值的引用）”。

你觉得你写这个函数和我说的东西相符吗？

2022-10-25 02:47 UTC, qiayuanliao commented on rm_common/include/rm_common/decision/power_limit.h
> +  double getLimitPower(const rm_msgs::ChassisCmd& chassis_cmd_)
@ye-luo-xi-tui 

- 这种 code style 问题也太欠敲打了。
- 他 pr 前你先看看他到底改对了没，我看他 传了个 const 引用 作为参数然后又 return 个 double 然后在外面赋值，是真的绷不住

2022-10-26 03:53 UTC, chenhuiYu00 commented on rm_common/include/rm_common/decision/power_limit.h
> +  double getLimitPower(const rm_msgs::ChassisCmd& chassis_cmd_)
手抽点了force push…

2022-10-26 12:16 UTC, qiayuanliao commented on rm_common/include/rm_common/decision/power_limit.h
> +  double getLimitPower(const rm_msgs::ChassisCmd& chassis_cmd_)
问题不大，记得就行

2022-10-26 12:31 UTC, qiayuanliao commented on rm_common/include/rm_common/decision/power_limit.h
> +  double getLimitPower(const rm_msgs::ChassisCmd& chassis_cmd_)
powerlimit 改对了。heatlimit 应该也要统一一样的形式？ @ye-luo-xi-tui 你觉得呢?

2022-10-29 02:57 UTC, qiayuanliao approved these changes
不错

2022-10-29 02:58 UTC, merged