Improve the Ui to reduce data transport
rm-controls/rm_control pull request #80
Opened 2022-10-22 07:00 UTC by ljq-lv

2022-10-22 11:51 UTC, Aung-xiao approved these changes

2022-10-22 12:03 UTC, L-SY approved these changes

2022-10-22 12:50 UTC, NaHCO3bc approved these changes

2022-10-22 13:17 UTC, 1moule approved these changes

2022-10-25 09:03 UTC, ye-luo-xi-tui commented on rm_referee/src/referee.cpp
> +  rm_msgs::CapacityData capacity_data_;
两个局部变量你用下划线？

2022-10-25 09:18 UTC, ye-luo-xi-tui commented on rm_referee/src/referee.cpp
> +          rm_msgs::GameStatus game_status_data_;
这里也是

2022-10-25 09:18 UTC, ye-luo-xi-tui commented on rm_referee/src/referee.cpp
> +          rm_msgs::DartStatus dart_status_data_;
还有好多地方都不合规范

2022-10-25 09:44 UTC, ye-luo-xi-tui commented on rm_referee/include/rm_referee/referee.h
> +    dart_status_pub_ = root_nh.advertise<rm_msgs::DartStatus>("/referee_dart_status_data", 1);
emmm你都想到在前面加个referee了，为什么不直接搞个referee的命名空间

2022-10-25 10:28 UTC, ljq-lv commented on rm_referee/include/rm_referee/referee.h
> +    dart_status_pub_ = root_nh.advertise<rm_msgs::DartStatus>("/referee_dart_status_data", 1);
蠢了

2022-10-28 13:04 UTC, ljq-lv commented
@ye-luo-xi-tui @chenhuiYu00  @Edwinlinks  @caijiefeng  qy哥催我勒

2022-10-29 04:42 UTC, ye-luo-xi-tui commented
你现在要解决合并冲突了

2022-10-29 04:47 UTC, ye-luo-xi-tui commented
啊这，format没过

2022-10-29 04:50 UTC, ljq-lv commented
> 啊这，format没过

github上合的 吐了 wait

2022-10-29 11:44 UTC, Edwinlinks commented on rm_referee/include/rm_referee/common/ui.h
> +  virtual void updateDartClientCmd(const rm_msgs::DartClientCmd::ConstPtr data, const ros::Time& last_get_){};
我看了一下，应该只有updateManualCmdData是共用的，我觉得只是这个放父类好一点，不用所有都弄在父类里面毕竟有很多都只是在某个类里面单独用到。

2022-10-29 12:17 UTC, ye-luo-xi-tui commented on rm_referee/include/rm_referee/common/ui.h
> +  explicit TargetTriggerChangeUi(ros::NodeHandle& nh, Base& base);
为什么有的地方需要调父类的构造函数有些又不需要，有点迷惑

2022-10-29 12:27 UTC, ye-luo-xi-tui commented on rm_referee/include/rm_referee/referee.h
> +    ros::NodeHandle referee_nh(root_nh, "/referee");
似乎不需要斜杠，不清楚加了斜杠会有什么影响

2022-10-29 12:41 UTC, ljq-lv commented on rm_referee/include/rm_referee/common/ui.h
> +  explicit TargetTriggerChangeUi(ros::NodeHandle& nh, Base& base);
具体哪里嘞

2022-10-29 12:41 UTC, ljq-lv commented on rm_referee/include/rm_referee/referee.h
> +    ros::NodeHandle referee_nh(root_nh, "/referee");
加了斜杠也可以 实际测过的

2022-10-29 12:43 UTC, ye-luo-xi-tui commented on rm_referee/include/rm_referee/common/ui.h
> +  explicit TargetTriggerChangeUi(ros::NodeHandle& nh, Base& base);
> 具体哪里嘞

就这一行啊，明明父类也有构造函数，结果这里不需要调用

2022-10-29 12:47 UTC, ljq-lv commented on rm_referee/include/rm_referee/common/ui.h
> +  explicit TargetTriggerChangeUi(ros::NodeHandle& nh, Base& base);
在cpp那调用勒

2022-10-29 12:47 UTC, ye-luo-xi-tui commented on rm_referee/src/main.cpp
> +  referee.referee_ui_ = new rm_referee::RefereeBase(nh, referee.base_);
这个能不能搞到`rm_referee::Referee`的构造函数里。

2022-10-29 12:54 UTC, ye-luo-xi-tui commented on rm_referee/include/rm_referee/common/ui.h
> +  explicit TargetTriggerChangeUi(ros::NodeHandle& nh, Base& base);
> 在cpp那调用勒

构造函数的定义全部放头文件里，不要东一块西一块

2022-10-29 12:57 UTC, ljq-lv commented on rm_referee/include/rm_referee/common/ui.h
> +  explicit TargetTriggerChangeUi(ros::NodeHandle& nh, Base& base);
> > 在cpp那调用勒
> 
> 构造函数的定义全部放头文件里，不要东一块西一块
有些初始化的时候 还要init一些东西的我就放在cpp，不需要额外初始化其他的我就放在h里面 这样子的

2022-10-29 12:59 UTC, ye-luo-xi-tui commented on rm_referee/include/rm_referee/common/ui.h
> +  explicit TargetTriggerChangeUi(ros::NodeHandle& nh, Base& base);
> > > 在cpp那调用勒
> > 
> > 
> > 构造函数的定义全部放头文件里，不要东一块西一块
> > 有些初始化的时候 还要init一些东西的我就放在cpp，不需要额外初始化其他的我就放在h里面 这样子的

放头文件

2022-10-29 13:01 UTC, ljq-lv commented on rm_referee/include/rm_referee/common/ui.h
> +  explicit TargetTriggerChangeUi(ros::NodeHandle& nh, Base& base);
ok

2022-10-29 13:12 UTC, ye-luo-xi-tui commented on rm_referee/include/rm_referee/referee.h
> +  Referee() : super_capacitor_(), last_get_(ros::Time::now())
这里这个super_capacitor_没有参数，应该不用调

2022-10-29 13:15 UTC, ye-luo-xi-tui commented on rm_referee/include/rm_referee/referee.h
> +    dart_status_pub_ = referee_nh.advertise<rm_msgs::DartStatus>("dart_status_data", 1);
ok，既然都传个nh进来了，这里全部用传进来的那个nh，不要用你的referee_nh

2022-10-29 13:16 UTC, ljq-lv commented on rm_referee/include/rm_referee/referee.h
> +    dart_status_pub_ = referee_nh.advertise<rm_msgs::DartStatus>("dart_status_data", 1);
1

2022-10-29 13:21 UTC, ye-luo-xi-tui commented on rm_referee/src/referee/referee_base.cpp
> -  base_.radar_data_ = data->data[0] * 10 + data->data[1];
好几个什么都不执行的函数是因为暂时没用到？

2022-10-29 13:23 UTC, ljq-lv commented on rm_referee/src/referee/referee_base.cpp
> -  base_.radar_data_ = data->data[0] * 10 + data->data[1];
是，有一些是之前留下来的ui功能，但是还没用，我这里也就还没用

2022-10-29 14:21 UTC, ye-luo-xi-tui commented on rm_referee/include/rm_referee/common/ui.h
>    std::map<std::string, Graph*> graph_vector_;
为什么有一个`Graph* graph_`和一个`std::map<std::string, Graph*> graph_vector_`？

2022-10-29 14:24 UTC, ye-luo-xi-tui commented on rm_referee/include/rm_referee/common/ui.h
>    std::map<std::string, Graph*> graph_vector_;
> 为什么有一个`Graph* graph_`和一个`std::map<std::string, Graph*> graph_vector_`？

`graph_vector_`是在哪被赋值的？为什么下面要遍历`graph_vector_`？

2022-10-29 14:28 UTC, ye-luo-xi-tui commented on rm_referee/include/rm_referee/referee.h
>    ros::Time last_get_data_;
从命名上看不出是个时间戳

2022-10-29 15:28 UTC, ljq-lv commented on rm_referee/include/rm_referee/common/ui.h
>    std::map<std::string, Graph*> graph_vector_;
vector是在uibase 的初始化里面 将配置文件中对应ui type的每个存到vector里面，然后因为最新的逻辑把每个ui都作为一个类 以前是把整个ui_type作为一个类。。然后再uitype的初始化中 会找到目标的 配置文件 然后存在graph里面

2022-10-29 15:28 UTC, ljq-lv commented on rm_referee/include/rm_referee/referee.h
>    ros::Time last_get_data_;
这些命名是以前传下来的 改成啥好d

2022-10-29 16:30 UTC, ye-luo-xi-tui commented on rm_referee/include/rm_referee/common/ui.h
>    std::map<std::string, Graph*> graph_vector_;
> vector是在uibase 的初始化里面 将配置文件中对应ui type的每个存到vector里面，然后因为最新的逻辑把每个ui都作为一个类 以前是把整个ui_type作为一个类。。然后再uitype的初始化中 会找到目标的 配置文件 然后存在graph里面

不对吧，怎么感觉有点多此一举的感觉。。
直接在父类就给graph赋好值不好吗。。非要存进一个vector然后子类再遍历一遍？

2022-10-29 16:45 UTC, ye-luo-xi-tui commented on rm_referee/src/referee/referee_base.cpp
> +  }
话说你在外部就已经获取过一次参数了，传个nh进去再获取一次不是浪费时间吗？你不如直接传个XmlRpc的常值引用进去？

2022-10-29 16:52 UTC, ljq-lv commented on rm_referee/include/rm_referee/common/ui.h
>    std::map<std::string, Graph*> graph_vector_;
这里的处理是这样的 uitype可以被分为两大类 一大类是被单独处理的 一大类是一起处理的（FIXUI）后者是需要用vector 前者就单独就行了 所以这里就base弄成vector 后面的 再搜索这样

2022-10-29 17:01 UTC, ljq-lv commented on rm_referee/include/rm_referee/common/ui.h
>    std::map<std::string, Graph*> graph_vector_;
可以

2022-10-30 04:35 UTC, ye-luo-xi-tui commented on rm_referee/src/referee/referee_base.cpp
> +      chassis_trigger_change_ui_ = new ChassisTriggerChangeUi(rpc_value, base_);
你传`rpc_value[i]["name"]`不好吗，非要整个传进去里面再遍历一遍

2022-10-30 04:42 UTC, ye-luo-xi-tui commented
还有注释两个斜杠就行了，有些地方你用了四个

2022-10-30 04:49 UTC, ljq-lv commented on rm_referee/src/referee/referee_base.cpp
> +      chassis_trigger_change_ui_ = new ChassisTriggerChangeUi(rpc_value, base_);
我这里的思路是想把他们搞成一个整体进去 然后再分 等等再改次吧

2022-10-30 05:02 UTC, ljq-lv commented on rm_referee/src/referee/referee_base.cpp
> +      chassis_trigger_change_ui_ = new ChassisTriggerChangeUi(rpc_value, base_);
> 还有注释两个斜杠就行了，有些地方你用了四个

oo 那些地方用四个是为了显色 更容易区分开来

2022-10-30 06:09 UTC, ye-luo-xi-tui commented on rm_referee/include/rm_referee/common/ui.h
> +      graph_ = new Graph(rpc_value["config"], base_, 1);
new之后不delete会造成内存泄漏，建议在析构函数里delete一下

2022-10-31 05:52 UTC, ljq-lv commented
@caijiefeng @chenhuiYu00 @Edwinlinks @ye-luo-xi-tui

2022-10-31 10:34 UTC, ye-luo-xi-tui commented on rm_referee/include/rm_referee/common/ui.h
> +      graph_ = new Graph(rpc_value["config"], base_, 1);
> new之后不delete会造成内存泄漏，建议在析构函数里delete一下

所以delete呢？new和delete是成对的。
算了算了不delete也行，我查了资料说你指针中途不指向其他地方就不会内存泄漏

2022-10-31 10:39 UTC, ljq-lv commented on rm_referee/include/rm_referee/common/ui.h
> +      graph_ = new Graph(rpc_value["config"], base_, 1);
> > new之后不delete会造成内存泄漏，建议在析构函数里delete一下
> 
> 所以delete呢？new和delete是成对的。 算了算了不delete也行，我查了资料说你指针中途不指向其他地方就不会内存泄漏

我referee_base里那些new的逻辑，主要是参考engineer_middleware里motion.h的逻辑。

2022-10-31 10:45 UTC, ye-luo-xi-tui commented on rm_referee/include/rm_referee/referee/referee_base.h
> +  virtual void capacityDataCallBack(const rm_msgs::CapacityData& capacity_data_, ros::Time& last_get_);
后面那个ros::Time 的参数改一下

2022-10-31 10:48 UTC, ye-luo-xi-tui commented on rm_referee/src/common/ui.cpp
> +  //  }
注释怎么回事

2022-10-31 10:56 UTC, ljq-lv commented on rm_referee/src/common/ui.cpp
> +  //  }
emmm 之前测试超电的时候加上的 现在删

2022-10-31 10:57 UTC, ye-luo-xi-tui commented on rm_referee/src/common/ui.cpp
> +    if (cap_power_ > 0.)
这两个条件可以写在同一个if的

2022-10-31 11:03 UTC, ye-luo-xi-tui commented on rm_referee/src/common/ui.cpp
> +  geometry_msgs::TransformStamped yaw_2_baselink;
yaw2base就可以了

2022-10-31 11:04 UTC, ye-luo-xi-tui commented on rm_referee/src/common/ui.cpp
>    }
为什么0和2画在相同位置1和3画在相同位置

2022-10-31 11:07 UTC, ljq-lv commented on rm_referee/src/common/ui.cpp
>    }
旧逻辑这么写的，实测的反馈是没有问题的。也不是相同位置吧 他set里面乘了getArmorId()

2022-10-31 11:10 UTC, ye-luo-xi-tui commented on rm_referee/src/referee/referee_base.cpp
> +  usleep(200000);
为什么不同类型的ui要分开添加并且添加完一种要休眠

2022-10-31 11:12 UTC, ljq-lv commented on rm_referee/src/referee/referee_base.cpp
> +  usleep(200000);
chenhui那版开始加上去的  他的描述好像是为了删除老的UI？？ @chenhuiYu00  你来具体解释一下吧

2022-10-31 11:13 UTC, ye-luo-xi-tui commented on rm_referee/src/referee/referee_base.cpp
>  }
这个函数干嘛的，没用的话为啥不删掉

2022-10-31 11:27 UTC, chenhuiYu00 commented on rm_referee/src/referee/referee_base.cpp
> +  usleep(200000);
> 

因为原来ui是按类装进容器里的，通过判断容器里有没有ui来决定要不要add;加休眠是考虑到ui一次性发太多会被挤掉，以前有过部分ui因为更新太快导致被挤掉而无法及时更新的情况

2022-10-31 11:42 UTC, ye-luo-xi-tui commented on rm_referee/src/referee/referee_base.cpp
> +  usleep(200000);
> > 
> 
> 因为原来ui是按类装进容器里的，通过判断容器里有没有ui来决定要不要add;加休眠是考虑到ui一次性发太多会被挤掉，以前有过部分ui因为更新太快导致被挤掉而无法及时更新的情况

那现在还需要吗？现在更新不需要休眠好像

2022-10-31 11:45 UTC, ye-luo-xi-tui commented on rm_referee/include/rm_referee/referee/referee_base.h
> +  virtual void capacityDataCallBack(const rm_msgs::CapacityData& capacity_data_, ros::Time& last_get_);
> 后面那个ros::Time 的参数改一下

我让你改的是参数名

2022-10-31 11:46 UTC, chenhuiYu00 commented on rm_referee/src/referee/referee_base.cpp
> +  usleep(200000);
> 

可以去掉后试一试add ui后屏幕上有没有漏的ui，没问题就可以去了。

2022-11-02 07:42 UTC, ljq-lv commented on rm_referee/src/referee/referee_base.cpp
> +  usleep(200000);
测过了 可删

2022-11-02 08:58 UTC, chenhuiYu00 approved these changes

2022-11-02 11:48 UTC, Edwinlinks commented on rm_referee/include/rm_referee/common/ui.h
> +  void updateManualCmdData(const rm_msgs::ManualToReferee::ConstPtr data);
updateManualCmdData 这个函数我觉得可以放父类好一点。

2022-11-03 08:32 UTC, caijiefeng approved these changes

2022-11-03 10:37 UTC, Edwinlinks approved these changes

2022-11-03 11:11 UTC, ye-luo-xi-tui approved these changes

2022-11-03 14:32 UTC, ljq-lv commented
> ui.cpp 里面咋有 上千行？我都加载不出来.. 不会把所有的ui类的实现都塞在里面了吧
雀氏ui类实现都在里面，ui.cpp里面放的都是各种ui具体的初始化 回调 和必要的数据处理

2022-11-03 15:46 UTC, ljq-lv commented
> ui.cpp 里面咋有 上千行？我都加载不出来.. 不会把所有的ui类的实现都塞在里面了吧

没有上千行那么离谱 505行

2022-11-03 17:08 UTC, qiayuanliao commented
> 

好好用 Markdown ....

2022-11-03 17:09 UTC, qiayuanliao commented
> > ui.cpp 里面咋有 上千行？我都加载不出来.. 不会把所有的ui类的实现都塞在里面了吧
> 
> 没有上千行那么离谱 505行

分开成两三个文件吧

2022-11-05 12:16 UTC, ljq-lv commented
@qiayuanliao

2022-11-07 02:39 UTC, ljq-lv commented
@qiayuanliao qy哥有空就看看呗

2022-11-09 06:05 UTC, qiayuanliao requested changes
receive_data 文件夹可能不是很必要? @ye-luo-xi-tui  你们讨论一下吧，一般要有多个文件或未来有多个文件才需要搞个文件夹的。你把 referee.cpp 改个名不就行了

2022-11-09 06:05 UTC, qiayuanliao commented on rm_referee/include/rm_referee/referee_base.h
> +#include "rm_common/decision/command_sender.h"
应该是尖括号合适点？

2022-11-09 06:05 UTC, qiayuanliao commented on rm_referee/include/rm_referee/referee_base.h
> +#include "rm_common/decision/command_sender.h"
common 应该在 referee 前面？ 我不确定

2022-11-24 13:29 UTC, ye-luo-xi-tui commented on rm_referee/CMakeLists.txt
> +FILE(GLOB ALL_SOURCES "src/*.cpp" "src/common/*.cpp" "src/referee/*.cpp" "src/ui/*.cpp")
没有referee文件夹了，这里改一下

2022-11-24 13:33 UTC, ye-luo-xi-tui commented on rm_referee/src/ui/flash_ui.cpp
> +void SpinFlashUi::updateChassisCmdData(const rm_msgs::ChassisCmd::ConstPtr data, const ros::Time& last_get_)
时间戳命名

2022-11-24 13:34 UTC, ye-luo-xi-tui commented on rm_referee/src/ui/flash_ui.cpp
> +void CoverFlashUi::updateManualCmdData(const rm_msgs::ManualToReferee::ConstPtr data, const ros::Time& last_get_)
同上

2022-11-24 13:34 UTC, ye-luo-xi-tui commented on rm_referee/src/ui/flash_ui.cpp
> +void ArmorFlashUi::updateRobotHurtData(const rm_msgs::RobotHurt data, const ros::Time& last_get_)
同上

2022-11-24 14:17 UTC, ye-luo-xi-tui commented on rm_referee/src/ui/flash_ui.cpp
> +void ArmorFlashUi::updateRobotHurtData(const rm_msgs::RobotHurt data, const ros::Time& last_get_data_time_)
形参加下划线，我看你是想被屌了

2022-11-24 14:45 UTC, ye-luo-xi-tui commented on rm_referee/include/rm_referee/ui/trigger_change_ui.h
> +#include "rm_common/decision/power_limit.h"
这个应该用尖括号

2022-11-24 14:51 UTC, ye-luo-xi-tui commented on rm_referee/include/rm_referee/ui/graph.h
> +#include "rm_common/ros_utilities.h"
这个也是，没记错的话别的项目头文件用尖括号

2022-11-24 15:03 UTC, merged